sudo: required
language: ruby
rvm:
  - 2.5.1
services:
  - mongodb
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - gem install bundler -v 1.16.1
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
